### ISSUE TITLE
Unhandled exception at 0x00007FFB0956BA99

### ISSUE THREAD

**Issue by The3dVehicleguy** [hadryansalles/Luz#30]
I keep trying to make the program work. I build the application in debug and release conditions to see if the compiled result works and every time it fails. 

I went in and started a debugging session to try and see what's going on and I get upon start of the Debug Session:

```
Unhandled exception at 0x00007FFB0956BA99 in Luz.exe: Microsoft C++ exception: nlohmann::json_abi_v3_11_3::detail::type_error at memory location 0x00000067D8FAE778.
```

I've looked into how to fix this but I cannot wrap my head around this problem. Anyone encountered this and figured out a solution to it?

**Comment by hadryansalles** [comment]
hey, thanks for reporting

indeed the default scene file was crashing
I updated it, please check latest [main](https://github.com/hadryansalles/Luz/tree/main) branch to make it work

**Comment by The3dVehicleguy** [comment]
just pull the main and tried to rebuild and run debug from Visual Studio and still getting an Unhandled exception.

```
The thread 47452 has exited with code 0 (0x0).
Exception thrown at 0x00007FF9A2FEFD8D (vcruntime140d.dll) in Luz.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Unhandled exception at 0x00007FF9A2FEFD8D (vcruntime140d.dll) in Luz.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

<HTML>
<body>


  | Name | Value | Type
-- | -- | -- | --
  | memcpy | 0x00007ff7eeb2073d {Luz.exe!memcpy} | void *
▶ | storage | {data={ size=0 } } | BinaryStorage &
▶ | this | 0x000000584ed2ec30 {j={m_data={m_type=object m_value={...} } } storage={data={ size=0 } } manager={impl=...} ...} | Serializer *
▶ | v | { size=4665600 } | std::vector<unsigned char,std::allocator<unsigned char>> &



</body>
</HTML>


I added you on discord earlier so if you want to figure this out together better we can.

**Comment by hadryansalles** [comment]
hey, checkout latest main, should be fixed now
